### ISSUE TITLE
Tests failing due to google.com old certificate expiring

### ISSUE THREAD

**Issue by fransla** [sensepost/apostille#1]
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Tue Jul 23 21:02:00 NZST 2019

Easy to bypass in the interim by commenting out lines 57 and 58 in ApostilleTest.java:
        //testSite(apostille, "google.com.pem");
        //dumpKeystore(ks);

**Comment by RoganDawes** [comment]
This was fixed by testing the cert as at a particular date. (when it was still valid).
